import { Ticket } from "./types";

export const ticketData: Ticket[] = [
  {
    id: 1,
    from: "SVO",
    to: "LED",
    company: "S7 Airlines",
    price: 12900,
    currency: "RUB",
    date: "20-02-2022",
    duration: 15,
    time: {
      startTime: "04:00",
      endTime: "12:00",
    },
    connectionAmount: 2,
  },
  {
    id: 2,
    from: "SVO",
    to: "LED",
    company: "Pobeda Airlines",
    price: 29780,
    currency: "RUB",
    date: "20-02-2022",
    duration: 2,
    time: {
      startTime: "04:30",
      endTime: "06:30",
    },
    connectionAmount: null,
  },
  {
    id: 3,
    from: "SVO",
    to: "LED",
    company: "Pobeda Airlines",
    price: 10500,
    currency: "RUB",
    date: "20-02-2022",
    duration: 4.08,
    time: {
      startTime: "04:50",
      endTime: "08:55",
    },
    connectionAmount: 1,
  },
  {
    id: 4,
    from: "SVO",
    to: "LED",
    company: "Red Wings",
    price: 18575,
    currency: "RUB",
    date: "20-02-2022",
    duration: 12.333,
    time: {
      startTime: "10-30",
      endTime: "22-50",
    },
    connectionAmount: 2,
  },
  {
    id: 5,
    from: "SVO",
    to: "LED",
    company: "S7 Airlines",
    price: 16549,
    currency: "RUB",
    date: "20-02-2022",
    duration: 2,
    time: {
      startTime: "18-50",
      endTime: "20-50",
    },
    connectionAmount: 0,
  },
];
